// AUTO-GENERATED by scripts/gen-schedule.mjs — do not edit by hand.
// Run `npm run gen:schedule` to refresh.

export type Race = {
  slug: string;
  round: number;
  name: string;
  countryCode: string;
  countryName: string;
  circuitShortName: string;
  startDate: string;
  endDate: string;
};

export type Season = {
  year: number;
  races: Race[];
  driversChampion: string | null;
  constructorsChampion: string | null;
  raceCount: number;
};

export const SCHEDULE: Season[] = [
  {
    "year": 2018,
    "races": [
      {
        "slug": "bahrain-2018",
        "round": 1,
        "name": "Bahrain Grand Prix",
        "countryCode": "BRN",
        "countryName": "Bahrain",
        "circuitShortName": "Sakhir",
        "startDate": "2018-04-06",
        "endDate": "2018-04-08"
      },
      {
        "slug": "china-2018",
        "round": 2,
        "name": "Chinese Grand Prix",
        "countryCode": "CHN",
        "countryName": "China",
        "circuitShortName": "Shanghai",
        "startDate": "2018-04-13",
        "endDate": "2018-04-15"
      },
      {
        "slug": "azerbaijan-2018",
        "round": 3,
        "name": "Azerbaijan Grand Prix",
        "countryCode": "AZE",
        "countryName": "Azerbaijan",
        "circuitShortName": "Baku",
        "startDate": "2018-04-27",
        "endDate": "2018-04-29"
      },
      {
        "slug": "spain-2018",
        "round": 4,
        "name": "Spanish Grand Prix",
        "countryCode": "ESP",
        "countryName": "Spain",
        "circuitShortName": "Catalunya",
        "startDate": "2018-05-11",
        "endDate": "2018-05-13"
      },
      {
        "slug": "monaco-2018",
        "round": 5,
        "name": "Monaco Grand Prix",
        "countryCode": "MON",
        "countryName": "Monaco",
        "circuitShortName": "Monte Carlo",
        "startDate": "2018-05-24",
        "endDate": "2018-05-27"
      },
      {
        "slug": "canada-2018",
        "round": 6,
        "name": "Canadian Grand Prix",
        "countryCode": "CAN",
        "countryName": "Canada",
        "circuitShortName": "Montreal",
        "startDate": "2018-06-08",
        "endDate": "2018-06-10"
      },
      {
        "slug": "france-2018",
        "round": 7,
        "name": "French Grand Prix",
        "countryCode": "FRA",
        "countryName": "France",
        "circuitShortName": "Paul Ricard",
        "startDate": "2018-06-22",
        "endDate": "2018-06-24"
      },
      {
        "slug": "austria-2018",
        "round": 8,
        "name": "Austrian Grand Prix",
        "countryCode": "AUT",
        "countryName": "Austria",
        "circuitShortName": "Spielberg",
        "startDate": "2018-06-29",
        "endDate": "2018-07-01"
      },
      {
        "slug": "great-britain-2018",
        "round": 9,
        "name": "British Grand Prix",
        "countryCode": "GBR",
        "countryName": "Great Britain",
        "circuitShortName": "Silverstone",
        "startDate": "2018-07-06",
        "endDate": "2018-07-08"
      },
      {
        "slug": "germany-2018",
        "round": 10,
        "name": "German Grand Prix",
        "countryCode": "GER",
        "countryName": "Germany",
        "circuitShortName": "Hockenheim",
        "startDate": "2018-07-20",
        "endDate": "2018-07-22"
      },
      {
        "slug": "hungary-2018",
        "round": 11,
        "name": "Hungarian Grand Prix",
        "countryCode": "HUN",
        "countryName": "Hungary",
        "circuitShortName": "Hungaroring",
        "startDate": "2018-07-27",
        "endDate": "2018-07-29"
      },
      {
        "slug": "belgium-2018",
        "round": 12,
        "name": "Belgian Grand Prix",
        "countryCode": "BEL",
        "countryName": "Belgium",
        "circuitShortName": "Spa-Francorchamps",
        "startDate": "2018-08-24",
        "endDate": "2018-08-26"
      },
      {
        "slug": "italy-2018",
        "round": 13,
        "name": "Italian Grand Prix",
        "countryCode": "ITA",
        "countryName": "Italy",
        "circuitShortName": "Monza",
        "startDate": "2018-08-31",
        "endDate": "2018-09-02"
      },
      {
        "slug": "singapore-2018",
        "round": 14,
        "name": "Singapore Grand Prix",
        "countryCode": "SGP",
        "countryName": "Singapore",
        "circuitShortName": "Singapore",
        "startDate": "2018-09-14",
        "endDate": "2018-09-16"
      },
      {
        "slug": "russia-2018",
        "round": 15,
        "name": "Russian Grand Prix",
        "countryCode": "RUS",
        "countryName": "Russia",
        "circuitShortName": "Sochi",
        "startDate": "2018-09-28",
        "endDate": "2018-09-30"
      },
      {
        "slug": "japan-2018",
        "round": 16,
        "name": "Japanese Grand Prix",
        "countryCode": "JPN",
        "countryName": "Japan",
        "circuitShortName": "Suzuka",
        "startDate": "2018-10-05",
        "endDate": "2018-10-07"
      },
      {
        "slug": "united-states-2018",
        "round": 17,
        "name": "United States Grand Prix",
        "countryCode": "USA",
        "countryName": "United States",
        "circuitShortName": "Austin",
        "startDate": "2018-10-19",
        "endDate": "2018-10-21"
      },
      {
        "slug": "mexico-2018",
        "round": 18,
        "name": "Mexican Grand Prix",
        "countryCode": "MEX",
        "countryName": "Mexico",
        "circuitShortName": "Mexico City",
        "startDate": "2018-10-26",
        "endDate": "2018-10-28"
      },
      {
        "slug": "brazil-2018",
        "round": 19,
        "name": "Brazilian Grand Prix",
        "countryCode": "BRA",
        "countryName": "Brazil",
        "circuitShortName": "Interlagos",
        "startDate": "2018-11-09",
        "endDate": "2018-11-11"
      },
      {
        "slug": "united-arab-emirates-2018",
        "round": 20,
        "name": "Abu Dhabi Grand Prix",
        "countryCode": "UAE",
        "countryName": "United Arab Emirates",
        "circuitShortName": "Yas Marina Circuit",
        "startDate": "2018-11-23",
        "endDate": "2018-11-25"
      }
    ],
    "driversChampion": "Lewis Hamilton",
    "constructorsChampion": "Mercedes",
    "raceCount": 20
  },
  {
    "year": 2019,
    "races": [
      {
        "slug": "australia-2019",
        "round": 1,
        "name": "Australian Grand Prix",
        "countryCode": "AUS",
        "countryName": "Australia",
        "circuitShortName": "Melbourne",
        "startDate": "2019-03-15",
        "endDate": "2019-03-17"
      },
      {
        "slug": "bahrain-2019",
        "round": 2,
        "name": "Bahrain Grand Prix",
        "countryCode": "BRN",
        "countryName": "Bahrain",
        "circuitShortName": "Sakhir",
        "startDate": "2019-03-29",
        "endDate": "2019-03-31"
      },
      {
        "slug": "china-2019",
        "round": 3,
        "name": "Chinese Grand Prix",
        "countryCode": "CHN",
        "countryName": "China",
        "circuitShortName": "Shanghai",
        "startDate": "2019-04-12",
        "endDate": "2019-04-14"
      },
      {
        "slug": "azerbaijan-2019",
        "round": 4,
        "name": "Azerbaijan Grand Prix",
        "countryCode": "AZE",
        "countryName": "Azerbaijan",
        "circuitShortName": "Baku",
        "startDate": "2019-04-26",
        "endDate": "2019-04-28"
      },
      {
        "slug": "spain-2019",
        "round": 5,
        "name": "Spanish Grand Prix",
        "countryCode": "ESP",
        "countryName": "Spain",
        "circuitShortName": "Catalunya",
        "startDate": "2019-05-10",
        "endDate": "2019-05-12"
      },
      {
        "slug": "monaco-2019",
        "round": 6,
        "name": "Monaco Grand Prix",
        "countryCode": "MON",
        "countryName": "Monaco",
        "circuitShortName": "Monte Carlo",
        "startDate": "2019-05-23",
        "endDate": "2019-05-26"
      },
      {
        "slug": "canada-2019",
        "round": 7,
        "name": "Canadian Grand Prix",
        "countryCode": "CAN",
        "countryName": "Canada",
        "circuitShortName": "Montreal",
        "startDate": "2019-06-07",
        "endDate": "2019-06-09"
      },
      {
        "slug": "france-2019",
        "round": 8,
        "name": "French Grand Prix",
        "countryCode": "FRA",
        "countryName": "France",
        "circuitShortName": "Paul Ricard",
        "startDate": "2019-06-21",
        "endDate": "2019-06-23"
      },
      {
        "slug": "austria-2019",
        "round": 9,
        "name": "Austrian Grand Prix",
        "countryCode": "AUT",
        "countryName": "Austria",
        "circuitShortName": "Spielberg",
        "startDate": "2019-06-28",
        "endDate": "2019-06-30"
      },
      {
        "slug": "great-britain-2019",
        "round": 10,
        "name": "British Grand Prix",
        "countryCode": "GBR",
        "countryName": "Great Britain",
        "circuitShortName": "Silverstone",
        "startDate": "2019-07-12",
        "endDate": "2019-07-14"
      },
      {
        "slug": "germany-2019",
        "round": 11,
        "name": "German Grand Prix",
        "countryCode": "GER",
        "countryName": "Germany",
        "circuitShortName": "Hockenheim",
        "startDate": "2019-07-26",
        "endDate": "2019-07-28"
      },
      {
        "slug": "hungary-2019",
        "round": 12,
        "name": "Hungarian Grand Prix",
        "countryCode": "HUN",
        "countryName": "Hungary",
        "circuitShortName": "Hungaroring",
        "startDate": "2019-08-02",
        "endDate": "2019-08-04"
      },
      {
        "slug": "belgium-2019",
        "round": 13,
        "name": "Belgian Grand Prix",
        "countryCode": "BEL",
        "countryName": "Belgium",
        "circuitShortName": "Spa-Francorchamps",
        "startDate": "2019-08-30",
        "endDate": "2019-09-01"
      },
      {
        "slug": "italy-2019",
        "round": 14,
        "name": "Italian Grand Prix",
        "countryCode": "ITA",
        "countryName": "Italy",
        "circuitShortName": "Monza",
        "startDate": "2019-09-06",
        "endDate": "2019-09-08"
      },
      {
        "slug": "singapore-2019",
        "round": 15,
        "name": "Singapore Grand Prix",
        "countryCode": "SGP",
        "countryName": "Singapore",
        "circuitShortName": "Singapore",
        "startDate": "2019-09-20",
        "endDate": "2019-09-22"
      },
      {
        "slug": "russia-2019",
        "round": 16,
        "name": "Russian Grand Prix",
        "countryCode": "RUS",
        "countryName": "Russia",
        "circuitShortName": "Sochi",
        "startDate": "2019-09-27",
        "endDate": "2019-09-29"
      },
      {
        "slug": "japan-2019",
        "round": 17,
        "name": "Japanese Grand Prix",
        "countryCode": "JPN",
        "countryName": "Japan",
        "circuitShortName": "Suzuka",
        "startDate": "2019-10-11",
        "endDate": "2019-10-13"
      },
      {
        "slug": "mexico-2019",
        "round": 18,
        "name": "Mexican Grand Prix",
        "countryCode": "MEX",
        "countryName": "Mexico",
        "circuitShortName": "Mexico City",
        "startDate": "2019-10-25",
        "endDate": "2019-10-27"
      },
      {
        "slug": "united-states-2019",
        "round": 19,
        "name": "United States Grand Prix",
        "countryCode": "USA",
        "countryName": "United States",
        "circuitShortName": "Austin",
        "startDate": "2019-11-01",
        "endDate": "2019-11-03"
      },
      {
        "slug": "brazil-2019",
        "round": 20,
        "name": "Brazilian Grand Prix",
        "countryCode": "BRA",
        "countryName": "Brazil",
        "circuitShortName": "Interlagos",
        "startDate": "2019-11-15",
        "endDate": "2019-11-17"
      },
      {
        "slug": "united-arab-emirates-2019",
        "round": 21,
        "name": "Abu Dhabi Grand Prix",
        "countryCode": "UAE",
        "countryName": "United Arab Emirates",
        "circuitShortName": "Yas Marina Circuit",
        "startDate": "2019-11-29",
        "endDate": "2019-12-01"
      }
    ],
    "driversChampion": "Lewis Hamilton",
    "constructorsChampion": "Mercedes",
    "raceCount": 21
  },
  {
    "year": 2020,
    "races": [
      {
        "slug": "spielberg-2020",
        "round": 1,
        "name": "Austrian Grand Prix",
        "countryCode": "AUT",
        "countryName": "Austria",
        "circuitShortName": "Spielberg",
        "startDate": "2020-07-03",
        "endDate": "2020-07-05"
      },
      {
        "slug": "spielberg-2020",
        "round": 2,
        "name": "Styrian Grand Prix",
        "countryCode": "AUT",
        "countryName": "Austria",
        "circuitShortName": "Spielberg",
        "startDate": "2020-07-10",
        "endDate": "2020-07-12"
      },
      {
        "slug": "hungary-2020",
        "round": 3,
        "name": "Hungarian Grand Prix",
        "countryCode": "HUN",
        "countryName": "Hungary",
        "circuitShortName": "Hungaroring",
        "startDate": "2020-07-17",
        "endDate": "2020-07-19"
      },
      {
        "slug": "silverstone-2020",
        "round": 4,
        "name": "British Grand Prix",
        "countryCode": "GBR",
        "countryName": "Great Britain",
        "circuitShortName": "Silverstone",
        "startDate": "2020-07-31",
        "endDate": "2020-08-02"
      },
      {
        "slug": "silverstone-2020",
        "round": 5,
        "name": "70th Anniversary Grand Prix",
        "countryCode": "GBR",
        "countryName": "Great Britain",
        "circuitShortName": "Silverstone",
        "startDate": "2020-08-07",
        "endDate": "2020-08-09"
      },
      {
        "slug": "spain-2020",
        "round": 6,
        "name": "Spanish Grand Prix",
        "countryCode": "ESP",
        "countryName": "Spain",
        "circuitShortName": "Catalunya",
        "startDate": "2020-08-14",
        "endDate": "2020-08-16"
      },
      {
        "slug": "belgium-2020",
        "round": 7,
        "name": "Belgian Grand Prix",
        "countryCode": "BEL",
        "countryName": "Belgium",
        "circuitShortName": "Spa-Francorchamps",
        "startDate": "2020-08-28",
        "endDate": "2020-08-30"
      },
      {
        "slug": "monza-2020",
        "round": 8,
        "name": "Italian Grand Prix",
        "countryCode": "ITA",
        "countryName": "Italy",
        "circuitShortName": "Monza",
        "startDate": "2020-09-04",
        "endDate": "2020-09-06"
      },
      {
        "slug": "mugello-2020",
        "round": 9,
        "name": "Tuscan Grand Prix",
        "countryCode": "ITA",
        "countryName": "Italy",
        "circuitShortName": "Mugello",
        "startDate": "2020-09-11",
        "endDate": "2020-09-13"
      },
      {
        "slug": "russia-2020",
        "round": 10,
        "name": "Russian Grand Prix",
        "countryCode": "RUS",
        "countryName": "Russia",
        "circuitShortName": "Sochi",
        "startDate": "2020-09-25",
        "endDate": "2020-09-27"
      },
      {
        "slug": "germany-2020",
        "round": 11,
        "name": "Eifel Grand Prix",
        "countryCode": "GER",
        "countryName": "Germany",
        "circuitShortName": "Nürburgring",
        "startDate": "2020-10-09",
        "endDate": "2020-10-11"
      },
      {
        "slug": "portugal-2020",
        "round": 12,
        "name": "Portuguese Grand Prix",
        "countryCode": "POR",
        "countryName": "Portugal",
        "circuitShortName": "Algarve International Circuit",
        "startDate": "2020-10-23",
        "endDate": "2020-10-25"
      },
      {
        "slug": "imola-2020",
        "round": 13,
        "name": "Emilia Romagna Grand Prix",
        "countryCode": "ITA",
        "countryName": "Italy",
        "circuitShortName": "Imola",
        "startDate": "2020-10-31",
        "endDate": "2020-11-01"
      },
      {
        "slug": "turkey-2020",
        "round": 14,
        "name": "Turkish Grand Prix",
        "countryCode": "TUR",
        "countryName": "Turkey",
        "circuitShortName": "Istanbul",
        "startDate": "2020-11-13",
        "endDate": "2020-11-15"
      },
      {
        "slug": "sakhir-2020",
        "round": 15,
        "name": "Bahrain Grand Prix",
        "countryCode": "BRN",
        "countryName": "Bahrain",
        "circuitShortName": "Sakhir",
        "startDate": "2020-11-27",
        "endDate": "2020-11-29"
      },
      {
        "slug": "sakhir-2020",
        "round": 16,
        "name": "Sakhir Grand Prix",
        "countryCode": "BRN",
        "countryName": "Bahrain",
        "circuitShortName": "Sakhir Outer Track",
        "startDate": "2020-12-04",
        "endDate": "2020-12-06"
      },
      {
        "slug": "united-arab-emirates-2020",
        "round": 17,
        "name": "Abu Dhabi Grand Prix",
        "countryCode": "UAE",
        "countryName": "United Arab Emirates",
        "circuitShortName": "Yas Marina Circuit",
        "startDate": "2020-12-11",
        "endDate": "2020-12-13"
      }
    ],
    "driversChampion": "Lewis Hamilton",
    "constructorsChampion": "Mercedes",
    "raceCount": 17
  },
  {
    "year": 2021,
    "races": [
      {
        "slug": "bahrain-2021",
        "round": 1,
        "name": "Bahrain Grand Prix",
        "countryCode": "BRN",
        "countryName": "Bahrain",
        "circuitShortName": "Sakhir",
        "startDate": "2021-03-26",
        "endDate": "2021-03-28"
      },
      {
        "slug": "imola-2021",
        "round": 2,
        "name": "Emilia Romagna Grand Prix",
        "countryCode": "ITA",
        "countryName": "Italy",
        "circuitShortName": "Imola",
        "startDate": "2021-04-16",
        "endDate": "2021-04-18"
      },
      {
        "slug": "portugal-2021",
        "round": 3,
        "name": "Portuguese Grand Prix",
        "countryCode": "POR",
        "countryName": "Portugal",
        "circuitShortName": "Algarve International Circuit",
        "startDate": "2021-04-30",
        "endDate": "2021-05-02"
      },
      {
        "slug": "spain-2021",
        "round": 4,
        "name": "Spanish Grand Prix",
        "countryCode": "ESP",
        "countryName": "Spain",
        "circuitShortName": "Catalunya",
        "startDate": "2021-05-07",
        "endDate": "2021-05-09"
      },
      {
        "slug": "monaco-2021",
        "round": 5,
        "name": "Monaco Grand Prix",
        "countryCode": "MON",
        "countryName": "Monaco",
        "circuitShortName": "Monte Carlo",
        "startDate": "2021-05-20",
        "endDate": "2021-05-23"
      },
      {
        "slug": "azerbaijan-2021",
        "round": 6,
        "name": "Azerbaijan Grand Prix",
        "countryCode": "AZE",
        "countryName": "Azerbaijan",
        "circuitShortName": "Baku",
        "startDate": "2021-06-04",
        "endDate": "2021-06-06"
      },
      {
        "slug": "france-2021",
        "round": 7,
        "name": "French Grand Prix",
        "countryCode": "FRA",
        "countryName": "France",
        "circuitShortName": "Paul Ricard",
        "startDate": "2021-06-18",
        "endDate": "2021-06-20"
      },
      {
        "slug": "spielberg-2021",
        "round": 8,
        "name": "Styrian Grand Prix",
        "countryCode": "AUT",
        "countryName": "Austria",
        "circuitShortName": "Spielberg",
        "startDate": "2021-06-25",
        "endDate": "2021-06-27"
      },
      {
        "slug": "spielberg-2021",
        "round": 9,
        "name": "Austrian Grand Prix",
        "countryCode": "AUT",
        "countryName": "Austria",
        "circuitShortName": "Spielberg",
        "startDate": "2021-07-02",
        "endDate": "2021-07-04"
      },
      {
        "slug": "great-britain-2021",
        "round": 10,
        "name": "British Grand Prix",
        "countryCode": "GBR",
        "countryName": "Great Britain",
        "circuitShortName": "Silverstone",
        "startDate": "2021-07-16",
        "endDate": "2021-07-18"
      },
      {
        "slug": "hungary-2021",
        "round": 11,
        "name": "Hungarian Grand Prix",
        "countryCode": "HUN",
        "countryName": "Hungary",
        "circuitShortName": "Hungaroring",
        "startDate": "2021-07-30",
        "endDate": "2021-08-01"
      },
      {
        "slug": "belgium-2021",
        "round": 12,
        "name": "Belgian Grand Prix",
        "countryCode": "BEL",
        "countryName": "Belgium",
        "circuitShortName": "Spa-Francorchamps",
        "startDate": "2021-08-27",
        "endDate": "2021-08-29"
      },
      {
        "slug": "netherlands-2021",
        "round": 13,
        "name": "Dutch Grand Prix",
        "countryCode": "NED",
        "countryName": "Netherlands",
        "circuitShortName": "Zandvoort",
        "startDate": "2021-09-03",
        "endDate": "2021-09-05"
      },
      {
        "slug": "monza-2021",
        "round": 14,
        "name": "Italian Grand Prix",
        "countryCode": "ITA",
        "countryName": "Italy",
        "circuitShortName": "Monza",
        "startDate": "2021-09-10",
        "endDate": "2021-09-12"
      },
      {
        "slug": "russia-2021",
        "round": 15,
        "name": "Russian Grand Prix",
        "countryCode": "RUS",
        "countryName": "Russia",
        "circuitShortName": "Sochi",
        "startDate": "2021-09-24",
        "endDate": "2021-09-26"
      },
      {
        "slug": "turkey-2021",
        "round": 16,
        "name": "Turkish Grand Prix",
        "countryCode": "TUR",
        "countryName": "Turkey",
        "circuitShortName": "Istanbul",
        "startDate": "2021-10-08",
        "endDate": "2021-10-10"
      },
      {
        "slug": "united-states-2021",
        "round": 17,
        "name": "United States Grand Prix",
        "countryCode": "USA",
        "countryName": "United States",
        "circuitShortName": "Austin",
        "startDate": "2021-10-22",
        "endDate": "2021-10-24"
      },
      {
        "slug": "mexico-2021",
        "round": 18,
        "name": "Mexico City Grand Prix",
        "countryCode": "MEX",
        "countryName": "Mexico",
        "circuitShortName": "Mexico City",
        "startDate": "2021-11-05",
        "endDate": "2021-11-07"
      },
      {
        "slug": "brazil-2021",
        "round": 19,
        "name": "São Paulo Grand Prix",
        "countryCode": "BRA",
        "countryName": "Brazil",
        "circuitShortName": "Interlagos",
        "startDate": "2021-11-12",
        "endDate": "2021-11-14"
      },
      {
        "slug": "qatar-2021",
        "round": 20,
        "name": "Qatar Grand Prix",
        "countryCode": "QAT",
        "countryName": "Qatar",
        "circuitShortName": "Losail",
        "startDate": "2021-11-19",
        "endDate": "2021-11-21"
      },
      {
        "slug": "saudi-arabia-2021",
        "round": 21,
        "name": "Saudi Arabian Grand Prix",
        "countryCode": "KSA",
        "countryName": "Saudi Arabia",
        "circuitShortName": "Jeddah",
        "startDate": "2021-12-03",
        "endDate": "2022-03-24"
      },
      {
        "slug": "united-arab-emirates-2021",
        "round": 22,
        "name": "Abu Dhabi Grand Prix",
        "countryCode": "UAE",
        "countryName": "United Arab Emirates",
        "circuitShortName": "Yas Marina Circuit",
        "startDate": "2021-12-10",
        "endDate": "2021-12-12"
      }
    ],
    "driversChampion": "Max Verstappen",
    "constructorsChampion": "Mercedes",
    "raceCount": 22
  },
  {
    "year": 2023,
    "races": [
      {
        "slug": "bahrain-2023",
        "round": 1,
        "name": "Bahrain Grand Prix",
        "countryCode": "BRN",
        "countryName": "Bahrain",
        "circuitShortName": "Sakhir",
        "startDate": "2023-03-03",
        "endDate": "2023-03-05"
      },
      {
        "slug": "saudi-arabia-2023",
        "round": 2,
        "name": "Saudi Arabian Grand Prix",
        "countryCode": "KSA",
        "countryName": "Saudi Arabia",
        "circuitShortName": "Jeddah",
        "startDate": "2023-03-17",
        "endDate": "2023-03-19"
      },
      {
        "slug": "australia-2023",
        "round": 3,
        "name": "Australian Grand Prix",
        "countryCode": "AUS",
        "countryName": "Australia",
        "circuitShortName": "Melbourne",
        "startDate": "2023-03-31",
        "endDate": "2023-04-02"
      },
      {
        "slug": "azerbaijan-2023",
        "round": 4,
        "name": "Azerbaijan Grand Prix",
        "countryCode": "AZE",
        "countryName": "Azerbaijan",
        "circuitShortName": "Baku",
        "startDate": "2023-04-28",
        "endDate": "2023-04-30"
      },
      {
        "slug": "miami-2023",
        "round": 5,
        "name": "Miami Grand Prix",
        "countryCode": "USA",
        "countryName": "United States",
        "circuitShortName": "Miami",
        "startDate": "2023-05-05",
        "endDate": "2023-05-07"
      },
      {
        "slug": "monaco-2023",
        "round": 6,
        "name": "Monaco Grand Prix",
        "countryCode": "MON",
        "countryName": "Monaco",
        "circuitShortName": "Monte Carlo",
        "startDate": "2023-05-26",
        "endDate": "2023-05-28"
      },
      {
        "slug": "spain-2023",
        "round": 7,
        "name": "Spanish Grand Prix",
        "countryCode": "ESP",
        "countryName": "Spain",
        "circuitShortName": "Catalunya",
        "startDate": "2023-06-02",
        "endDate": "2023-06-04"
      },
      {
        "slug": "canada-2023",
        "round": 8,
        "name": "Canadian Grand Prix",
        "countryCode": "CAN",
        "countryName": "Canada",
        "circuitShortName": "Montreal",
        "startDate": "2023-06-16",
        "endDate": "2023-06-18"
      },
      {
        "slug": "austria-2023",
        "round": 9,
        "name": "Austrian Grand Prix",
        "countryCode": "AUT",
        "countryName": "Austria",
        "circuitShortName": "Spielberg",
        "startDate": "2023-06-30",
        "endDate": "2023-07-02"
      },
      {
        "slug": "great-britain-2023",
        "round": 10,
        "name": "British Grand Prix",
        "countryCode": "GBR",
        "countryName": "Great Britain",
        "circuitShortName": "Silverstone",
        "startDate": "2023-07-07",
        "endDate": "2023-07-09"
      },
      {
        "slug": "hungary-2023",
        "round": 11,
        "name": "Hungarian Grand Prix",
        "countryCode": "HUN",
        "countryName": "Hungary",
        "circuitShortName": "Hungaroring",
        "startDate": "2023-07-21",
        "endDate": "2023-07-23"
      },
      {
        "slug": "belgium-2023",
        "round": 12,
        "name": "Belgian Grand Prix",
        "countryCode": "BEL",
        "countryName": "Belgium",
        "circuitShortName": "Spa-Francorchamps",
        "startDate": "2023-07-28",
        "endDate": "2023-07-30"
      },
      {
        "slug": "netherlands-2023",
        "round": 13,
        "name": "Dutch Grand Prix",
        "countryCode": "NED",
        "countryName": "Netherlands",
        "circuitShortName": "Zandvoort",
        "startDate": "2023-08-25",
        "endDate": "2023-08-27"
      },
      {
        "slug": "italy-2023",
        "round": 14,
        "name": "Italian Grand Prix",
        "countryCode": "ITA",
        "countryName": "Italy",
        "circuitShortName": "Monza",
        "startDate": "2023-09-01",
        "endDate": "2023-09-03"
      },
      {
        "slug": "singapore-2023",
        "round": 15,
        "name": "Singapore Grand Prix",
        "countryCode": "SGP",
        "countryName": "Singapore",
        "circuitShortName": "Singapore",
        "startDate": "2023-09-15",
        "endDate": "2023-09-17"
      },
      {
        "slug": "japan-2023",
        "round": 16,
        "name": "Japanese Grand Prix",
        "countryCode": "JPN",
        "countryName": "Japan",
        "circuitShortName": "Suzuka",
        "startDate": "2023-09-22",
        "endDate": "2023-09-24"
      },
      {
        "slug": "qatar-2023",
        "round": 17,
        "name": "Qatar Grand Prix",
        "countryCode": "QAT",
        "countryName": "Qatar",
        "circuitShortName": "Lusail",
        "startDate": "2023-10-06",
        "endDate": "2023-10-08"
      },
      {
        "slug": "austin-2023",
        "round": 18,
        "name": "United States Grand Prix",
        "countryCode": "USA",
        "countryName": "United States",
        "circuitShortName": "Austin",
        "startDate": "2023-10-20",
        "endDate": "2023-10-22"
      },
      {
        "slug": "mexico-2023",
        "round": 19,
        "name": "Mexico City Grand Prix",
        "countryCode": "MEX",
        "countryName": "Mexico",
        "circuitShortName": "Mexico City",
        "startDate": "2023-10-27",
        "endDate": "2023-10-29"
      },
      {
        "slug": "brazil-2023",
        "round": 20,
        "name": "São Paulo Grand Prix",
        "countryCode": "BRA",
        "countryName": "Brazil",
        "circuitShortName": "Interlagos",
        "startDate": "2023-11-03",
        "endDate": "2023-11-05"
      },
      {
        "slug": "las-vegas-2023",
        "round": 21,
        "name": "Las Vegas Grand Prix",
        "countryCode": "USA",
        "countryName": "United States",
        "circuitShortName": "Las Vegas",
        "startDate": "2023-11-16",
        "endDate": "2023-11-18"
      },
      {
        "slug": "united-arab-emirates-2023",
        "round": 22,
        "name": "Abu Dhabi Grand Prix",
        "countryCode": "UAE",
        "countryName": "United Arab Emirates",
        "circuitShortName": "Yas Marina Circuit",
        "startDate": "2023-11-24",
        "endDate": "2023-11-26"
      }
    ],
    "driversChampion": "Max Verstappen",
    "constructorsChampion": "Red Bull Racing",
    "raceCount": 22
  },
  {
    "year": 2024,
    "races": [
      {
        "slug": "spain-2024",
        "round": 1,
        "name": "Spanish Grand Prix",
        "countryCode": "ESP",
        "countryName": "Spain",
        "circuitShortName": "Catalunya",
        "startDate": "2024-06-21",
        "endDate": "2024-06-23"
      },
      {
        "slug": "austria-2024",
        "round": 2,
        "name": "Austrian Grand Prix",
        "countryCode": "AUT",
        "countryName": "Austria",
        "circuitShortName": "Spielberg",
        "startDate": "2024-06-28",
        "endDate": "2024-06-30"
      },
      {
        "slug": "great-britain-2024",
        "round": 3,
        "name": "British Grand Prix",
        "countryCode": "GBR",
        "countryName": "Great Britain",
        "circuitShortName": "Silverstone",
        "startDate": "2024-07-05",
        "endDate": "2024-07-07"
      },
      {
        "slug": "hungary-2024",
        "round": 4,
        "name": "Hungarian Grand Prix",
        "countryCode": "HUN",
        "countryName": "Hungary",
        "circuitShortName": "Hungaroring",
        "startDate": "2024-07-19",
        "endDate": "2024-07-21"
      },
      {
        "slug": "belgium-2024",
        "round": 5,
        "name": "Belgian Grand Prix",
        "countryCode": "BEL",
        "countryName": "Belgium",
        "circuitShortName": "Spa-Francorchamps",
        "startDate": "2024-07-26",
        "endDate": "2024-07-28"
      },
      {
        "slug": "netherlands-2024",
        "round": 6,
        "name": "Dutch Grand Prix",
        "countryCode": "NED",
        "countryName": "Netherlands",
        "circuitShortName": "Zandvoort",
        "startDate": "2024-08-23",
        "endDate": "2024-08-25"
      },
      {
        "slug": "italy-2024",
        "round": 7,
        "name": "Italian Grand Prix",
        "countryCode": "ITA",
        "countryName": "Italy",
        "circuitShortName": "Monza",
        "startDate": "2024-08-30",
        "endDate": "2024-09-01"
      },
      {
        "slug": "azerbaijan-2024",
        "round": 8,
        "name": "Azerbaijan Grand Prix",
        "countryCode": "AZE",
        "countryName": "Azerbaijan",
        "circuitShortName": "Baku",
        "startDate": "2024-09-13",
        "endDate": "2024-09-15"
      },
      {
        "slug": "singapore-2024",
        "round": 9,
        "name": "Singapore Grand Prix",
        "countryCode": "SGP",
        "countryName": "Singapore",
        "circuitShortName": "Singapore",
        "startDate": "2024-09-20",
        "endDate": "2024-09-22"
      },
      {
        "slug": "austin-2024",
        "round": 10,
        "name": "United States Grand Prix",
        "countryCode": "USA",
        "countryName": "United States",
        "circuitShortName": "Austin",
        "startDate": "2024-10-18",
        "endDate": "2024-10-20"
      },
      {
        "slug": "mexico-2024",
        "round": 11,
        "name": "Mexico City Grand Prix",
        "countryCode": "MEX",
        "countryName": "Mexico",
        "circuitShortName": "Mexico City",
        "startDate": "2024-10-25",
        "endDate": "2024-10-27"
      },
      {
        "slug": "brazil-2024",
        "round": 12,
        "name": "São Paulo Grand Prix",
        "countryCode": "BRA",
        "countryName": "Brazil",
        "circuitShortName": "Interlagos",
        "startDate": "2024-11-01",
        "endDate": "2024-11-03"
      },
      {
        "slug": "las-vegas-2024",
        "round": 13,
        "name": "Las Vegas Grand Prix",
        "countryCode": "USA",
        "countryName": "United States",
        "circuitShortName": "Las Vegas",
        "startDate": "2024-11-21",
        "endDate": "2024-11-23"
      },
      {
        "slug": "qatar-2024",
        "round": 14,
        "name": "Qatar Grand Prix",
        "countryCode": "QAT",
        "countryName": "Qatar",
        "circuitShortName": "Lusail",
        "startDate": "2024-11-29",
        "endDate": "2024-12-01"
      },
      {
        "slug": "united-arab-emirates-2024",
        "round": 15,
        "name": "Abu Dhabi Grand Prix",
        "countryCode": "UAE",
        "countryName": "United Arab Emirates",
        "circuitShortName": "Yas Marina Circuit",
        "startDate": "2024-12-06",
        "endDate": "2024-12-08"
      }
    ],
    "driversChampion": "Max Verstappen",
    "constructorsChampion": "McLaren",
    "raceCount": 15
  },
  {
    "year": 2025,
    "races": [
      {
        "slug": "australia-2025",
        "round": 1,
        "name": "Australian Grand Prix",
        "countryCode": "AUS",
        "countryName": "Australia",
        "circuitShortName": "Melbourne",
        "startDate": "2025-03-14",
        "endDate": "2025-03-16"
      },
      {
        "slug": "china-2025",
        "round": 2,
        "name": "Chinese Grand Prix",
        "countryCode": "CHN",
        "countryName": "China",
        "circuitShortName": "Shanghai",
        "startDate": "2025-03-21",
        "endDate": "2025-03-23"
      },
      {
        "slug": "japan-2025",
        "round": 3,
        "name": "Japanese Grand Prix",
        "countryCode": "JPN",
        "countryName": "Japan",
        "circuitShortName": "Suzuka",
        "startDate": "2025-04-04",
        "endDate": "2025-04-06"
      },
      {
        "slug": "bahrain-2025",
        "round": 4,
        "name": "Bahrain Grand Prix",
        "countryCode": "BRN",
        "countryName": "Bahrain",
        "circuitShortName": "Sakhir",
        "startDate": "2025-04-11",
        "endDate": "2025-04-13"
      },
      {
        "slug": "saudi-arabia-2025",
        "round": 5,
        "name": "Saudi Arabian Grand Prix",
        "countryCode": "KSA",
        "countryName": "Saudi Arabia",
        "circuitShortName": "Jeddah",
        "startDate": "2025-04-18",
        "endDate": "2025-04-20"
      },
      {
        "slug": "miami-2025",
        "round": 6,
        "name": "Miami Grand Prix",
        "countryCode": "USA",
        "countryName": "United States",
        "circuitShortName": "Miami",
        "startDate": "2025-05-02",
        "endDate": "2025-05-04"
      },
      {
        "slug": "imola-2025",
        "round": 7,
        "name": "Emilia Romagna Grand Prix",
        "countryCode": "ITA",
        "countryName": "Italy",
        "circuitShortName": "Imola",
        "startDate": "2025-05-16",
        "endDate": "2025-05-18"
      },
      {
        "slug": "monaco-2025",
        "round": 8,
        "name": "Monaco Grand Prix",
        "countryCode": "MON",
        "countryName": "Monaco",
        "circuitShortName": "Monte Carlo",
        "startDate": "2025-05-23",
        "endDate": "2025-05-25"
      },
      {
        "slug": "spain-2025",
        "round": 9,
        "name": "Spanish Grand Prix",
        "countryCode": "ESP",
        "countryName": "Spain",
        "circuitShortName": "Catalunya",
        "startDate": "2025-05-30",
        "endDate": "2025-06-01"
      },
      {
        "slug": "canada-2025",
        "round": 10,
        "name": "Canadian Grand Prix",
        "countryCode": "CAN",
        "countryName": "Canada",
        "circuitShortName": "Montreal",
        "startDate": "2025-06-13",
        "endDate": "2025-06-15"
      },
      {
        "slug": "austria-2025",
        "round": 11,
        "name": "Austrian Grand Prix",
        "countryCode": "AUT",
        "countryName": "Austria",
        "circuitShortName": "Spielberg",
        "startDate": "2025-06-27",
        "endDate": "2025-06-29"
      },
      {
        "slug": "united-kingdom-2025",
        "round": 12,
        "name": "British Grand Prix",
        "countryCode": "GBR",
        "countryName": "United Kingdom",
        "circuitShortName": "Silverstone",
        "startDate": "2025-07-04",
        "endDate": "2025-07-06"
      },
      {
        "slug": "belgium-2025",
        "round": 13,
        "name": "Belgian Grand Prix",
        "countryCode": "BEL",
        "countryName": "Belgium",
        "circuitShortName": "Spa-Francorchamps",
        "startDate": "2025-07-25",
        "endDate": "2025-07-27"
      },
      {
        "slug": "hungary-2025",
        "round": 14,
        "name": "Hungarian Grand Prix",
        "countryCode": "HUN",
        "countryName": "Hungary",
        "circuitShortName": "Hungaroring",
        "startDate": "2025-08-01",
        "endDate": "2025-08-03"
      },
      {
        "slug": "netherlands-2025",
        "round": 15,
        "name": "Dutch Grand Prix",
        "countryCode": "NED",
        "countryName": "Netherlands",
        "circuitShortName": "Zandvoort",
        "startDate": "2025-08-29",
        "endDate": "2025-08-31"
      },
      {
        "slug": "monza-2025",
        "round": 16,
        "name": "Italian Grand Prix",
        "countryCode": "ITA",
        "countryName": "Italy",
        "circuitShortName": "Monza",
        "startDate": "2025-09-05",
        "endDate": "2025-09-07"
      },
      {
        "slug": "azerbaijan-2025",
        "round": 17,
        "name": "Azerbaijan Grand Prix",
        "countryCode": "AZE",
        "countryName": "Azerbaijan",
        "circuitShortName": "Baku",
        "startDate": "2025-09-19",
        "endDate": "2025-09-21"
      },
      {
        "slug": "singapore-2025",
        "round": 18,
        "name": "Singapore Grand Prix",
        "countryCode": "SGP",
        "countryName": "Singapore",
        "circuitShortName": "Singapore",
        "startDate": "2025-10-03",
        "endDate": "2025-10-05"
      },
      {
        "slug": "austin-2025",
        "round": 19,
        "name": "United States Grand Prix",
        "countryCode": "USA",
        "countryName": "United States",
        "circuitShortName": "Austin",
        "startDate": "2025-10-17",
        "endDate": "2025-10-19"
      },
      {
        "slug": "mexico-2025",
        "round": 20,
        "name": "Mexico City Grand Prix",
        "countryCode": "MEX",
        "countryName": "Mexico",
        "circuitShortName": "Mexico City",
        "startDate": "2025-10-24",
        "endDate": "2025-10-26"
      },
      {
        "slug": "brazil-2025",
        "round": 21,
        "name": "São Paulo Grand Prix",
        "countryCode": "BRA",
        "countryName": "Brazil",
        "circuitShortName": "Interlagos",
        "startDate": "2025-11-07",
        "endDate": "2025-11-09"
      },
      {
        "slug": "las-vegas-2025",
        "round": 22,
        "name": "Las Vegas Grand Prix",
        "countryCode": "USA",
        "countryName": "United States",
        "circuitShortName": "Las Vegas",
        "startDate": "2025-11-20",
        "endDate": "2025-11-22"
      },
      {
        "slug": "qatar-2025",
        "round": 23,
        "name": "Qatar Grand Prix",
        "countryCode": "QAT",
        "countryName": "Qatar",
        "circuitShortName": "Lusail",
        "startDate": "2025-11-28",
        "endDate": "2025-11-30"
      },
      {
        "slug": "united-arab-emirates-2025",
        "round": 24,
        "name": "Abu Dhabi Grand Prix",
        "countryCode": "UAE",
        "countryName": "United Arab Emirates",
        "circuitShortName": "Yas Marina Circuit",
        "startDate": "2025-12-05",
        "endDate": "2025-12-07"
      }
    ],
    "driversChampion": "Lando Norris",
    "constructorsChampion": "McLaren",
    "raceCount": 24
  },
  {
    "year": 2026,
    "races": [
      {
        "slug": "australia-2026",
        "round": 1,
        "name": "Australian Grand Prix",
        "countryCode": "AUS",
        "countryName": "Australia",
        "circuitShortName": "Melbourne",
        "startDate": "2026-03-06",
        "endDate": "2026-03-08"
      },
      {
        "slug": "china-2026",
        "round": 2,
        "name": "Chinese Grand Prix",
        "countryCode": "CHN",
        "countryName": "China",
        "circuitShortName": "Shanghai",
        "startDate": "2026-03-13",
        "endDate": "2026-03-15"
      },
      {
        "slug": "japan-2026",
        "round": 3,
        "name": "Japanese Grand Prix",
        "countryCode": "JPN",
        "countryName": "Japan",
        "circuitShortName": "Suzuka",
        "startDate": "2026-03-27",
        "endDate": "2026-03-29"
      }
    ],
    "driversChampion": null,
    "constructorsChampion": null,
    "raceCount": 3
  }
];
